package bean;
// Generated Jun 2, 2017 8:37:06 PM by Hibernate Tools 4.3.1



        ;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable
{


     private int depId;
     private String
             depName;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Department() {
    }

	
    public Department(int depId) {
        this.depId = depId;
    }
    public Department(int depId, String
            depName, Set<Employee> employees) {
       this.depId = depId;
       this.depName = depName;
       this.employees = employees;
    }
   
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }
    public String
         getDepName() {
        return this.depName;
    }
    
    public void setDepName(String
            depName) {
        this.depName = depName;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


